# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/sdm710-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter sdm710-common,$(TARGET_DEVICE)),)

endif
